from __future__ import annotations

import argparse
import os
import sys
import time
from typing import Any

import httpx


DEFAULT_TIMEOUT_SECONDS = 120
DEFAULT_POLL_INTERVAL_SECONDS = 2


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Run a live smoke check against the ExtConvert API.")
    parser.add_argument(
        "--api-base-url",
        default=os.getenv("NEXT_PUBLIC_API_BASE_URL") or os.getenv("API_BASE_URL"),
        help="Base URL of the deployed API, for example https://your-service.onrender.com",
    )
    parser.add_argument(
        "--target-format",
        default="pdf",
        help="Target format to request during the conversion smoke test.",
    )
    parser.add_argument(
        "--timeout-seconds",
        type=int,
        default=DEFAULT_TIMEOUT_SECONDS,
        help="Maximum number of seconds to wait for the batch job to finish.",
    )
    parser.add_argument(
        "--poll-interval-seconds",
        type=int,
        default=DEFAULT_POLL_INTERVAL_SECONDS,
        help="How often to poll the job status endpoint.",
    )
    return parser


def _require_base_url(value: str | None) -> str:
    if not value:
        raise SystemExit("Missing API base URL. Pass --api-base-url or set NEXT_PUBLIC_API_BASE_URL.")
    return value.rstrip("/")


def _check_health(client: httpx.Client) -> dict[str, Any]:
    response = client.get("/api/health")
    response.raise_for_status()
    payload = response.json()
    if payload.get("status") != "healthy":
        raise SystemExit(f"Health check failed: {payload}")
    return payload


def _submit_batch(client: httpx.Client, target_format: str) -> dict[str, Any]:
    content = b"Smoke test file generated by scripts/smoke_check.py\n"
    files = {"files": ("smoke-check.txt", content, "text/plain")}
    data = {"file_ids": "smoke_check_001"}
    response = client.post("/api/convert/batch", params={"target_format": target_format}, files=files, data=data)
    response.raise_for_status()
    payload = response.json()
    if "batch_id" not in payload:
        raise SystemExit(f"Batch submission returned an unexpected payload: {payload}")
    return payload


def _wait_for_job(client: httpx.Client, batch_id: str, timeout_seconds: int, poll_interval_seconds: int) -> dict[str, Any]:
    deadline = time.monotonic() + timeout_seconds
    last_payload: dict[str, Any] | None = None

    while time.monotonic() < deadline:
        response = client.get(f"/api/jobs/{batch_id}")
        response.raise_for_status()
        payload = response.json()
        last_payload = payload
        if payload.get("status") in {"done", "partial", "failed"}:
            return payload
        time.sleep(poll_interval_seconds)

    raise SystemExit(f"Timed out waiting for batch {batch_id}. Last payload: {last_payload}")


def _check_download(client: httpx.Client, batch_id: str, file_id: str) -> None:
    response = client.get(f"/api/jobs/{batch_id}/download/{file_id}", follow_redirects=False)
    if response.status_code != 307:
        raise SystemExit(f"Download endpoint returned {response.status_code} instead of 307.")

    location = response.headers.get("location")
    if not location:
        raise SystemExit("Download redirect is missing a Location header.")


def main() -> int:
    parser = _build_parser()
    args = parser.parse_args()
    base_url = _require_base_url(args.api_base_url)

    with httpx.Client(base_url=base_url, timeout=30.0) as client:
        health = _check_health(client)
        print(f"health ok: storage_backend={health.get('storage_backend')}, active_jobs={health.get('active_jobs')}")

        batch = _submit_batch(client, args.target_format)
        batch_id = str(batch["batch_id"])
        print(f"submitted batch: {batch_id}")

        final_payload = _wait_for_job(client, batch_id, args.timeout_seconds, args.poll_interval_seconds)
        print(f"job status: {final_payload.get('status')}")

        results = final_payload.get("results") or []
        if not results:
            raise SystemExit(f"Job completed without results: {final_payload}")

        first_result = results[0]
        file_id = str(first_result.get("file_id") or "")
        if not file_id:
            raise SystemExit(f"Job result missing file_id: {first_result}")

        if final_payload.get("status") != "failed":
            _check_download(client, batch_id, file_id)
            print(f"download redirect ok for file_id={file_id}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())